def extract_title(data): return data["name"]
def extract_concentration(data): return data["concentration"]
def extract_ingredients(data): return data["key_ingredients"]
def extract_benefits(data): return data["benefits"]
def extract_usage(data): return data["how_to_use"]
def extract_price(data): return data["price"]
def extract_skin_type(data): return data["skin_type"]
def extract_side_effects(data): return data["side_effects"]
